# Generated by Django 5.2.16 on 2026-08-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='Promotion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='shop.promotiontype'),
        ),
    ]
